package command

import "net/http"

func ReadSauna() {

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	resp, err := http.Get("http://www.tarlab.fi/sensors/temperature1")
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
}
